<?php
/**
 * Type
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

/**
 * Type Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Type
{
    /**
     * Possible values of this enum
     */
    const SENT = 'Sent';
    const OPENED = 'Opened';
    const LINK_CLICKED = 'LinkClicked';
    const FORWARD = 'Forward';
    const UNSUBSCRIBED = 'Unsubscribed';
    const BOUNCED = 'Bounced';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SENT,
            self::OPENED,
            self::LINK_CLICKED,
            self::FORWARD,
            self::UNSUBSCRIBED,
            self::BOUNCED,
        ];
    }
}


